### ISSUE TITLE
Cache not clearing on monterey Apple Silicon

### ISSUE THREAD

**Issue by Dannypeja** [ghostjuza/open-bushfire#17]
Installed on Macbook Pro M1 Pro 2021. 
Full Drive Access is granted.
Bushfire is run via Rosetta-2 and seems to be working. Browser History can be deleted but cookies remain. 
Every time at startup the system integrity message is displayed although full drive acess is granted (I believe that should do the job?).

**Comment by icew4y** [comment]
> Installed on Macbook Pro M1 Pro 2021.
> Full Drive Access is granted.
> Bushfire is run via Rosetta-2 and seems to be working. Browser History can be deleted but cookies remain.
> Every time at startup the system integrity message is displayed although full drive acess is granted (I believe that should do the job?).

It works in this link, I'll put it below:
https://github.com/icew4y/open-bushfire/releases/tag/Build2022-05-11

**Comment by andreasbica** [comment]
Great work. It looks like fixed.

**Comment by andreasbica** [comment]
Have to merge your changes ...

**Comment by andreasbica** [comment]
Can y create a PR please ?

**Comment by icew4y** [comment]
> Great work. It looks like fixed.

Yeah, thank you, it was not a big deal, I just basically replaced the newer version of the library ‘Sparkle’ and rebuild the project, as simple as that.

**Comment by andreasbica** [comment]
I will build a new release today ...
