### ISSUE TITLE
Cookies will be not removed after quitting Safari

### ISSUE THREAD

**Issue by andreasbica** [ghostjuza/open-bushfire#19]
On macOS 12.x (Monterey) cookies are not cleanly removed after closing Safari.

**Comment by icew4y** [comment]
I think Safari has changed the way to preserve cookies, I don't know where it is and how it works, but I have temporarily written an application to do so. I know it's dumb, but it works for me because I need this desperately.
https://github.com/icew4y/open-bushfire/commit/84dff17a064f761a71331acec6ce3f38b2853e62

**Comment by andreasbica** [comment]
It's not dumb 😝 y know how we can fix that for Bushfire and many user have this benefit. Can y tell me which steps I have to implement? Then I will fix this issue soon... provided you want that ?!

**Comment by icew4y** [comment]
> It's not dumb 😝 y know how we can fix that for Bushfire and many user have this benefit. Can y tell me which steps I have to implement? Then I will fix this issue soon... provided you want that ?!

I finally found the location where Safari preserve the cookies on macOS Monterey by using FSMonitor. I've created a pull request, I've also tested the code on Monterey and it works for me, if there is something wrong please forgive me(to be honest, this is the first time I create a pull request.)

**Comment by icew4y** [comment]
And a weird thing happened,  I cloned the latest version of you repository and the build was succeeded, but I couldn't run the application through Xcode, it shows an error:
`dyld[2334]: Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
  Referenced from: /Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/Bushfire
  Reason: tried: '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file)
(lldb) 
`

**Comment by andreasbica** [comment]
> 

It look like nice. 

> 

Don't worry, it work fine ... a new release is out. I testet on macOS 12.3 (Intel). All cookies deleted :)

**Comment by andreasbica** [comment]
> And a weird thing happened, I cloned the latest version of you repository and the build was succeeded, but I couldn't run the application through Xcode, it shows an error:
> `dyld[2334]: Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle Referenced from: /Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/Bushfire Reason: tried: '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file) (lldb)`

I don't get this error ! Maybe y have to set a Code Signing.

**Comment by andreasbica** [comment]
> And a weird thing happened, I cloned the latest version of you repository and the build was succeeded, but I couldn't run the application through Xcode, it shows an error:
> `dyld[2334]: Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle Referenced from: /Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/Bushfire Reason: tried: '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file) (lldb)`

*That will fix the build issue !!!*

**NOTE:** I have to do this on my Mac mini (Intel) with macOS 10.14.6

<img width="708" alt="Bildschirmfoto 2022-05-14 um 12 56 31" src="https://user-images.githubusercontent.com/1547159/168422854-7fbba927-8c07-41c3-8631-33c2dad4019b.png">

**Comment by andreasbica** [comment]
and this are my signing settings:

<img width="538" alt="Bildschirmfoto 2022-05-14 um 13 00 35" src="https://user-images.githubusercontent.com/1547159/168422944-5e4620ce-c9e4-4f44-8c5e-90845448db2c.png">

**Comment by icew4y** [comment]
> and this are my signing settings:
> 
> <img alt="Bildschirmfoto 2022-05-14 um 13 00 35" width="538" src="https://user-images.githubusercontent.com/1547159/168422944-5e4620ce-c9e4-4f44-8c5e-90845448db2c.png">

I did the same thing as you mentioned, I changed 'Sparkle.framework' with 'Embed Without Signing', I also change the Signing team to 'None', still no luck, and by the way, I was running on a Apple Silicon Macbook, here's the screenshot that the problem I have met while I was trying to run the application.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17697557/168428448-5154c790-1713-4a03-8e6d-24bc3bfcf15f.png">


Enclosing the output:

`
dyld[2411]: Library not loaded: @rpath/Sparkle.framework/Versions/B/Sparkle
  Referenced from: /Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/Bushfire
  Reason: tried: '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Sparkle.framework/Versions/B/Sparkle' (no such file), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/MacOS/../Frameworks/Sparkle.framework/Versions/B/Sparkle' (code signature in <4D947E39-B8F6-33EC-A4A7-577BC1680430> '/Users/louiswong/Library/Developer/Xcode/DerivedData/OpenBushfire-citxdiqgkkvcrkhcuzwjjpshmgxl/Build/Products/Debug/Bushfire.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle' not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)), '/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file), '/System/Library/Frameworks/Sparkle.framework/Versions/B/Sparkle' (no such file)
(lldb) 
`

**Comment by andreasbica** [comment]
Hm! Strange! I work also with a Apple Silicon MacBook... yesterday I updated my Xcode App (to 13.3.1 13E500a) with dependent components ... maybe is this the reason ...

**Comment by icew4y** [comment]
> Hm! Strange! I work also with a Apple Silicon MacBook... yesterday I updated my Xcode App (to 13.3.1 13E500a) with dependent components ... maybe is this the reason ...

Maybe it isn't the reason, I am also using Xcode Version 13.3.1 (13E500a).

**Comment by andreasbica** [comment]
It could be an Xcode bug .... or somewhere there is a completely different problem.
it would not be the first time ... I get the same issue on that ...

<img width="1273" alt="Bildschirmfoto 2022-05-14 um 17 08 32" src="https://user-images.githubusercontent.com/1547159/168433575-cf125914-094c-42c6-96b8-910f388e25af.png">

**Comment by andreasbica** [comment]
... and I think the latest Sparkle version is in Delta status.

**Comment by andreasbica** [comment]
HI @icew4y .... this works for me ... now I can debug the app ...

<img width="659" alt="Bildschirmfoto 2022-05-15 um 17 36 57" src="https://user-images.githubusercontent.com/1547159/168481132-cb8cc3de-9eb3-457b-80d6-a82db570fbe9.png">

**Comment by icew4y** [comment]
> HI @icew4y .... this works for me ... now I can debug the app ...
> 
> <img alt="Bildschirmfoto 2022-05-15 um 17 36 57" width="659" src="https://user-images.githubusercontent.com/1547159/168481132-cb8cc3de-9eb3-457b-80d6-a82db570fbe9.png">

Yeah, it worked for me by changing the Signing Certificate to Development, thanks for letting me know!
