### ISSUE TITLE
Changed code-signature in build-2022.28?

### ISSUE THREAD

**Issue by suschizu** [ghostjuza/open-bushfire#29]
Hey - I've noticed that the code signature has changed in the latest release from:
Andreas Bica (8CA8N668FU) 
to:
Andreas Bica (V67A8H8669)

Can you confirm this? Thanks

**Comment by andreasbica** [comment]
Hi, what relevance should that have? Do you have anything special in mind?

**Comment by core-code** [comment]
> Hi, what relevance should that have? Do you have anything special in mind?

the changed code signature is an obvious security issue and raises the question whether the new release is 'real' or generated by an attacker that managed to take over the github project.

**Comment by andreasbica** [comment]
> > Hi, what relevance should that have? Do you have anything special in mind?
> 
> the changed code signature is an obvious security issue and raises the question whether the new release is 'real' or generated by an attacker that managed to take over the github project.

It's me. If you have any safety concerns or suggestions, feel very free to let me know ...

**Comment by suschizu** [comment]
ok thanks … no concerns! I just wanted to be sure that this isn't a corrupted build :)
